aws_region               = "us-east-1"                # 리소스를 배포할 AWS 리전
aws_profile              = "my-profile"               # 인증에 사용할 AWS CLI 프로파일
private_dns_name         = "test.private.example.com" # Private DNS의 도메인 이름
test_record_ip_1         = "10.0.0.11"                # 첫 번째 테스트 레코드가 가리킬 IP 주소
test_record_ip_2         = "10.0.0.12"                # 두 번째 테스트 레코드가 가리킬 IP 주소
instance_type            = "t2.micro"                 # EC2 인스턴스 유형
pub_key_file_path        = "~/.ssh/my-key.pub"        # EC2 인스턴스에 사용할 공개 키 파일의 경로
vpc_name                 = "private-dns-test-vpc"     # 생성할 VPC의 이름
vpc_cidr_block           = "10.0.0.0/16"              # VPC에 사용할 CIDR 블록 (예: 10.0.0.0/16)
public_subnet_cidr       = "10.0.0.0/24"              # 퍼블릭 서브넷에 사용할 CIDR 블록 (예: 10.0.0.0/24)
subnet_availability_zone = "us-east-1a"               # 서브넷을 배치할 가용 영역
